### ISSUE TITLE
Hide nodes that are not "unlocked"

### ISSUE THREAD

**Issue by markfloryan** [markfloryan/ACAS#10]
Nodes (topics) should have two states:

unlocked: normal, student can interact with that node
locked: Not viewable at all. Student has not unlocked pre-requisites.

Nodes unlock and are viewable by students once all pre-requisite nodes are at competency or higher.

**Comment by dwp7kp** [comment]
**Branch:**
gradeDisplay

**Currently:** 
System only shows nodes that are at competency or higher and their immediate leaves.

**Todo:**
I don't think it will enforce multiple parent nodes

**Issues:**
If we plan to allow automatic grading for CS courses, it's possible a student could have a prior node at competency and then fail it (with a null pointer error or something). This would re-lock farther nodes and mess up drawing the tree. Example below. 

Full tree view
![image](https://user-images.githubusercontent.com/42259908/104996973-d547a000-59f6-11eb-83a3-c75906fde661.png)

Student view if they had passed graphs, a star, and fourth topic and later fail a star.
![image](https://user-images.githubusercontent.com/42259908/104997364-79314b80-59f7-11eb-803a-55df382e7893.png)
This happens because node 'fourth topic' is still technically passing. What should we do about this?

**Comment by dwp7kp** [comment]
**Branch:**
gradeDisplay

**Currently:**
System only shows nodes that are at competency or higher and their immediate leaves. Enforces passing all parent nodes.

**Todo:**
Resolve issue of later failing a prerequisite node.

**Issues**
Graph gets tangled if topics are complicated. Try to prevent crossing lines. Example:

![image](https://user-images.githubusercontent.com/42259908/104998566-746d9700-59f9-11eb-89f6-75f04fc86a49.png)

**Comment by dwp7kp** [comment]
We decided the graph would no longer hide locked nodes. Tree breaking is no longer an issue because all nodes are always present. Moving graph edge crossing to a new issue.
